Restrict ssh key file permissions
Otherwise you will get this error when pushing to Try:

```
Creating temporary commit for remote...

pushing to ssh://hg.mozilla.org/try

remote: Warning: Permanently added the RSA host key for IP address '63.245.208.203' to the list of known hosts.

remote: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

remote: @         WARNING: UNPROTECTED PRIVATE KEY FILE!          @

remote: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

remote: Permissions 0644 for '/root/.ssh/id_rsa_experiments_pusher' are too open.

remote: It is required that your private key files are NOT accessible by others.

remote: This private key will be ignored.

remote: Load key "/root/.ssh/id_rsa_experiments_pusher": bad permissions

remote: Permission denied (publickey).

temporary commit removed, repository restored

abort: no suitable response from remote hg!

Error running mach:

The details of the failure are as follows:

CalledProcessError: Command '(u'/usr/local/bin/hg', u'push-to-try', u'-m', u'try: -b do -p linux64 -u crashtest,firefox-ui-functional,geckoview,geckoview-junit,jsreftest,marionette,marionette-e10s,mochitests,reftest,robocop,web-platform-tests,xpcshell -t none --artifact\n\nPushed via `mach try syntax`')' returned non-zero exit status 255

  File "/repo/mozilla-central/tools/tryselect/mach_commands.py", line 100, in try_default

    'try', subcommand=sub, context=self._mach_context, argv=argv, **kwargs)

  File "/repo/mozilla-central/python/mach/mach/registrar.py", line 138, in dispatch

    return self._run_command_handler(handler, context=context, **kwargs)

  File "/repo/mozilla-central/python/mach/mach/registrar.py", line 95, in _run_command_handler

    result = fn(**kwargs)

  File "/repo/mozilla-central/tools/tryselect/mach_commands.py", line 256, in try_syntax

    return at.run(**kwargs)

  File "/repo/mozilla-central/tools/tryselect/selectors/syntax.py", line 623, in run

    closed_tree=kwargs["closed_tree"])

  File "/repo/mozilla-central/tools/tryselect/push.py", line 133, in push_to_try

    vcs.push_to_try(commit_message)

  File "/repo/mozilla-central/python/mozversioncontrol/mozversioncontrol/__init__.py", line 351, in push_to_try

    subprocess.check_call((self._tool, 'push-to-try', '-m', message), cwd=self.path)

  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call

    raise CalledProcessError(retcode, cmd)
```